### PR TITLE
Player Destruction & Robot Destruction HUD updates

### PR DESCRIPTION
**Pull request by Kruphixx**
- Added support for Robot Destruction mode (because why not)
- Added Selbyen HUD icons for PD
- Fixed some misalignment issues in the PD HUD

### CODE REVIEW

**Comment by FlaminSarge** [comment]
May be better if the 'drop zone open' icon used a box instead of the default... shape. Otherwise looks great.

**Comment by Kruphixx** [comment]
@FlaminSarge How's this?

Screenshot 2024-01-10 205139

**Comment by FlaminSarge** [comment]
Looks good. If I remember correctly, the arrow icon gets replaced with other things on different maps e.g. Pumpkins on some halloween maps, so I'm not quite sure what the best way to handle it is.

**Comment by FlaminSarge** [comment]
(I was right, see https://youtu.be/vrhBTo0k76k?t=102 for the custom one on Farmageddon; if you think it's useful, can probably just stick it centered above the box with no background).

**Comment by Kruphixx** [comment]
> (I was right, see https://youtu.be/vrhBTo0k76k?t=102 for the custom one on Farmageddon; its state also changes based on whether the zone is open or not. If you think it's useful, can probably just stick it centered above the box with no background).

Okay I did some changes, I couldn't get the icon to look good above the box so I put it back in the box instead and I think the result is quite nice.

If all looks good I'll push a commit.

Screenshot 2024-01-11 122607

Screenshot 2024-01-11 122619

**Pull request merged**
